name: Deploy to Web Server

on:
  push:
    branches:
      - ${{ secrets.MAIN_BRANCH }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Web Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git fetch origin ${{ secrets.MAIN_BRANCH }} && git reset --hard origin/${{ secrets.MAIN_BRANCH }}"

